# Generated by Django 3.1.6 on 2021-02-22 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_title', models.CharField(max_length=30)),
                ('cat_desc', models.CharField(max_length=50)),
                ('cat_image', models.ImageField(default='', upload_to='cat_images')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=30)),
                ('post_desc', models.CharField(max_length=50)),
                ('post_img', models.ImageField(upload_to='post_images')),
                ('date_posted', models.DateTimeField()),
                ('img_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.category')),
            ],
        ),
    ]
