# Generated by Django 3.1.6 on 2021-02-23 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(default='', primary_key=True, serialize=False)),
                ('article_title', models.CharField(max_length=30)),
                ('article_author', models.CharField(max_length=20)),
                ('article_desc', models.TextField()),
                ('article_content', models.TextField(default='')),
                ('article_main_image', models.ImageField(upload_to='article_main_images')),
                ('date_posted', models.DateTimeField()),
                ('article_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.category')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_images', models.ImageField(upload_to='article_images')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.article')),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
