# Generated by Django 3.1.6 on 2021-02-23 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20210223_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_title', models.CharField(max_length=30)),
                ('cat_desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_title', models.CharField(max_length=30)),
                ('cat_desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=30)),
                ('post_desc', models.CharField(max_length=50)),
                ('post_image', models.ImageField(upload_to='GalleryPosts')),
                ('date_posted', models.DateTimeField()),
                ('post_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.gallerycategory')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_content',
        ),
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_main_image',
            field=models.ImageField(upload_to='ArticleImages/MainImage'),
        ),
        migrations.AlterField(
            model_name='articleimages',
            name='article_images',
            field=models.ImageField(upload_to='ArticleImages'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='articlecontent',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.articlecategory'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
